// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://deoxrdicmklsgaqzsybm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlb3hyZGljbWtsc2dhcXpzeWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTU4NTksImV4cCI6MjA2NjUzMTg1OX0.HCt68Ud2OXLQRAgobo9I2IYL7KrNiKuq9yCX3A5dqKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);